### ISSUE TITLE
BAGULA

### ISSUE THREAD

**Issue by Lindsaydoodle** [BabayVadimovich/SMSCallBomber#1]
AttributeError: module 'config' has no attribute 
'Python310\lib\site-packages\smscallbomber\service.py", line 8, in username
    names = cfg.names
AttributeError: module 'config' has no attribute 'names'names'

**Comment by Matveydok234234324** [comment]
It will be fixed tomorrow

**Comment by BabayVadimovich** [comment]
Fixed
